server:
  port: 8080
  timeout: 30s

db:
  mysql:
    host: localhost
    port: 3306
    username: user
    password: secret
    database: artihub

log:
  level: debug
  format: json
  # output: stdout
  output: file
  dir: ./logs
  file: app.log.json